language: java
jdk:
    - openjdk8
cache:
    directories:
        -  "$HOME/.m2"
        
before_install:
   - cp .travis.settings.xml $HOME/.m2/settings.xml
   
jobs:
   - stage: Package
     name: "Run Tests"
     script:
          - mvn clean package  
          
   - stage: Deploy #stage type
     name: "Deploy stage" #stage name
     script:
          - mvn clean deploy -DskipTests 

notifications:
    email:
        recipients:
            - yadevkrishna1998@gmail.coom
        on_success: always
